<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Book Tickets — PULSE Events Singapore</title>
        <?php include "inc/head.inc.php" ?>
    </head>
    <body>

        <?php include "inc/nav.inc.php" ?>

        <div class="booking-page-wrapper">
            <div class="container" style="max-width: 1100px;">

                <!-- Step Progress -->
                <div class="booking-steps" id="bookingSteps">
                    <div class="booking-step active" data-step="1">
                        <div class="step-num">1</div>
                        <span class="step-label">Seats</span>
                    </div>
                    <div class="booking-step" data-step="2">
                        <div class="step-num">2</div>
                        <span class="step-label">Details</span>
                    </div>
                    <div class="booking-step" data-step="3">
                        <div class="step-num">3</div>
                        <span class="step-label">Payment</span>
                    </div>
                    <div class="booking-step" data-step="4">
                        <div class="step-num">4</div>
                        <span class="step-label">Confirm</span>
                    </div>
                </div>

                <!-- Event Summary Bar -->
                <div class="booking-event-bar">
                    <div>
                        <div class="booking-event-name">Guns N' Roses — World Tour 2026</div>
                        <div class="booking-event-meta">📍 Singapore Indoor Stadium &nbsp;·&nbsp; 18 Apr 2026, 8:00 PM</div>
                    </div>
                    <span class="tag-chip" style="border-color:rgba(248,244,238,0.25);color:rgba(248,244,238,0.75);background:transparent;">Rock</span>
                </div>

                <!-- ── STEP 1: Seat Selection ── -->
                <div class="booking-panel active" id="step1">
                    <div class="booking-layout">
                        <div>
                            <!-- Ticket Type -->
                            <div class="ticket-types-grid">
                                <div class="ticket-type-card selected" data-type="cat1" data-price="228">
                                    <div class="ticket-tier">Cat 1</div>
                                    <div class="ticket-name">Premium Floor</div>
                                    <div class="ticket-price">S$228</div>
                                    <div class="ticket-avail">142 available</div>
                                </div>
                                <div class="ticket-type-card" data-type="cat2" data-price="148">
                                    <div class="ticket-tier">Cat 2</div>
                                    <div class="ticket-name">Lower Tier</div>
                                    <div class="ticket-price">S$148</div>
                                    <div class="ticket-avail">380 available</div>
                                </div>
                                <div class="ticket-type-card" data-type="cat3" data-price="98">
                                    <div class="ticket-tier">Cat 3</div>
                                    <div class="ticket-name">Upper Tier</div>
                                    <div class="ticket-price">S$98</div>
                                    <div class="ticket-avail">510 available</div>
                                </div>
                            </div>

                            <!-- Seat Map -->
                            <div class="seat-map-container">
                                <div class="seat-map-stage">— Stage —</div>
                                <div class="seat-map-grid" id="seatMap">
                                    <!-- Rows A–F, 10 seats each — generated by JS -->
                                </div>
                                <div class="seat-legend">
                                    <div class="seat-legend-item">
                                        <div class="seat-legend-dot available"></div>Available
                                    </div>
                                    <div class="seat-legend-item">
                                        <div class="seat-legend-dot selected"></div>Selected
                                    </div>
                                    <div class="seat-legend-item">
                                        <div class="seat-legend-dot taken"></div>Taken
                                    </div>
                                </div>
                            </div>

                            <div class="booking-nav" style="justify-content:flex-end;">
                                <button class="btn-booking-next" id="toStep2" disabled>
                                    Continue
                                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2 6H10M10 6L7 3M10 6L7 9" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>
                                </button>
                            </div>
                        </div>

                        <!-- Order Summary -->
                        <div class="order-summary-card">
                            <div class="order-summary-title">Order Summary</div>
                            <div id="orderLines">
                                <div class="order-empty">Select seats to begin</div>
                            </div>
                            <div class="order-total" id="orderTotal" style="display:none;">
                                <span>Total</span>
                                <span id="totalAmount">S$0</span>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- ── STEP 2: Your Details ── -->
                <div class="booking-panel" id="step2">
                    <div class="booking-layout">
                        <div>
                            <div class="booking-form-section">
                                <div class="booking-form-title">Your Details</div>
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <label class="form-label">First Name</label>
                                        <input type="text" class="form-control" placeholder="Jane" id="firstName">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Last Name</label>
                                        <input type="text" class="form-control" placeholder="Doe" id="lastName">
                                    </div>
                                    <div class="col-12">
                                        <label class="form-label">Email Address</label>
                                        <input type="email" class="form-control" placeholder="jane@example.com" id="emailAddr">
                                    </div>
                                    <div class="col-12">
                                        <label class="form-label">Phone Number</label>
                                        <input type="tel" class="form-control" placeholder="+65 9123 4567" id="phoneNum">
                                    </div>
                                </div>
                            </div>
                            <div class="booking-nav">
                                <button class="btn-booking-back" id="back1">
                                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M10 6H2M2 6L5 3M2 6L5 9" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>
                                    Back
                                </button>
                                <button class="btn-booking-next" id="toStep3">
                                    Continue
                                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2 6H10M10 6L7 3M10 6L7 9" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>
                                </button>
                            </div>
                        </div>
                        <div class="order-summary-card">
                            <div class="order-summary-title">Order Summary</div>
                            <div id="orderLines2"></div>
                            <div class="order-total">
                                <span>Total</span>
                                <span id="totalAmount2">S$0</span>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- ── STEP 3: Payment ── -->
                <div class="booking-panel" id="step3">
                    <div class="booking-layout">
                        <div>
                            <div class="booking-form-section">
                                <div class="booking-form-title">Payment Method</div>

                                <div class="payment-methods">
                                    <button class="payment-pill active" data-method="card">
                                        💳 Credit / Debit Card
                                    </button>
                                    <button class="payment-pill" data-method="paynow">
                                        🇸🇬 PayNow
                                    </button>
                                    <button class="payment-pill" data-method="grabpay">
                                        🟢 GrabPay
                                    </button>
                                </div>

                                <div id="cardFields">
                                    <div class="mb-3">
                                        <label class="form-label">Cardholder Name</label>
                                        <input type="text" class="form-control" placeholder="Jane Doe">
                                    </div>
                                    <div class="mb-3">
                                        <label class="form-label">Card Number</label>
                                        <input type="text" class="form-control" placeholder="1234 5678 9012 3456" maxlength="19" id="cardNumber">
                                    </div>
                                    <div class="card-input-row">
                                        <div>
                                            <label class="form-label">Expiry Date</label>
                                            <input type="text" class="form-control" placeholder="MM / YY" maxlength="7">
                                        </div>
                                        <div>
                                            <label class="form-label">CVV</label>
                                            <input type="text" class="form-control" placeholder="•••" maxlength="4">
                                        </div>
                                    </div>
                                </div>

                                <div id="paynowFields" style="display:none;">
                                    <div style="text-align:center;padding:32px 0;">
                                        <div style="font-size:3.5rem;margin-bottom:12px;">📱</div>
                                        <p style="color:var(--pulse-muted);font-size:0.88rem;">A PayNow QR code will be shown after you proceed.<br>Complete payment within 10 minutes.</p>
                                    </div>
                                </div>

                                <div id="grabpayFields" style="display:none;">
                                    <div style="text-align:center;padding:32px 0;">
                                        <div style="font-size:3.5rem;margin-bottom:12px;">🟢</div>
                                        <p style="color:var(--pulse-muted);font-size:0.88rem;">You'll be redirected to the GrabPay app to complete your payment.</p>
                                    </div>
                                </div>
                            </div>

                            <div class="booking-nav">
                                <button class="btn-booking-back" id="back2">
                                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M10 6H2M2 6L5 3M2 6L5 9" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>
                                    Back
                                </button>
                                <button class="btn-booking-next" id="toStep4">
                                    Pay Now
                                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2 6H10M10 6L7 3M10 6L7 9" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>
                                </button>
                            </div>
                        </div>
                        <div class="order-summary-card">
                            <div class="order-summary-title">Order Summary</div>
                            <div id="orderLines3"></div>
                            <div class="order-total">
                                <span>Total</span>
                                <span id="totalAmount3">S$0</span>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- ── STEP 4: Success ── -->
                <div class="booking-panel" id="step4">
                    <div class="booking-success">
                        <div class="success-icon">🎉</div>
                        <div class="success-title">Booking Confirmed!</div>
                        <div class="success-ref" id="bookingRef">PULSE-2026-00001</div>
                        <p class="success-body">
                            Your tickets are confirmed. A confirmation and e-ticket have been sent to your email address. Present your QR code at the venue entrance.
                        </p>
                        <div style="display:flex;gap:12px;justify-content:center;flex-wrap:wrap;">
                            <a href="index.php" class="btn-accent">Back to Home</a>
                            <button onclick="window.print()" class="hero-btn-secondary">Download Ticket</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <?php include "inc/footer.inc.php" ?>

        <script>
        document.addEventListener("DOMContentLoaded", function () {
            initBookingSeatMap();
            initTicketTypes();
            initBookingSteps();
            initPaymentMethods();
        });

        // ---- Seat map ----
        const ROWS = ['A','B','C','D','E','F','G'];
        const SEATS_PER_ROW = 12;
        const takenSeats = new Set(['A3','A4','B7','C1','C2','D5','D6','E9','F3','F10','G2','G11']);
        const selectedSeats = new Set();
        let ticketPrice = 228;

        function initBookingSeatMap() {
            const map = document.getElementById('seatMap');
            if (!map) return;
            map.innerHTML = '';
            ROWS.forEach(row => {
                const rowEl = document.createElement('div');
                rowEl.className = 'seat-row';
                const label = document.createElement('span');
                label.className = 'seat-row-label';
                label.textContent = row;
                rowEl.appendChild(label);
                for (let s = 1; s <= SEATS_PER_ROW; s++) {
                    const id = row + s;
                    const seat = document.createElement('button');
                    seat.className = 'seat' + (takenSeats.has(id) ? ' taken' : '');
                    seat.dataset.id = id;
                    seat.title = 'Row ' + row + ' Seat ' + s;
                    seat.addEventListener('click', function () {
                        if (this.classList.contains('taken')) return;
                        if (this.classList.contains('selected')) {
                            this.classList.remove('selected');
                            selectedSeats.delete(id);
                        } else {
                            if (selectedSeats.size >= 8) return;
                            this.classList.add('selected');
                            selectedSeats.add(id);
                        }
                        updateOrderSummary();
                    });
                    rowEl.appendChild(seat);
                }
                map.appendChild(rowEl);
            });
        }

        function updateOrderSummary() {
            const count = selectedSeats.size;
            const total = count * ticketPrice;
            const hasSeats = count > 0;

            document.getElementById('toStep2').disabled = !hasSeats;

            const lines = document.getElementById('orderLines');
            const totalEl = document.getElementById('orderTotal');
            const amountEl = document.getElementById('totalAmount');

            if (!hasSeats) {
                lines.innerHTML = '<div class="order-empty">Select seats to begin</div>';
                totalEl.style.display = 'none';
                return;
            }
            lines.innerHTML = Array.from(selectedSeats).map(s =>
                `<div class="order-line"><span>Seat ${s}</span><span>S$${ticketPrice}</span></div>`
            ).join('') + `<div class="order-line"><span style="font-size:0.7rem;color:var(--pulse-muted)">Booking fee</span><span>S$${count * 3}</span></div>`;

            totalEl.style.display = 'flex';
            amountEl.textContent = 'S$' + (total + count * 3);
            syncSummaries();
        }

        function syncSummaries() {
            const src = document.getElementById('orderLines').innerHTML;
            const total = document.getElementById('totalAmount').textContent;
            ['orderLines2','orderLines3'].forEach(id => {
                const el = document.getElementById(id);
                if (el) el.innerHTML = src;
            });
            ['totalAmount2','totalAmount3'].forEach(id => {
                const el = document.getElementById(id);
                if (el) el.textContent = total;
            });
        }

        // ---- Ticket type cards ----
        function initTicketTypes() {
            document.querySelectorAll('.ticket-type-card').forEach(card => {
                card.addEventListener('click', function () {
                    document.querySelectorAll('.ticket-type-card').forEach(c => c.classList.remove('selected'));
                    this.classList.add('selected');
                    ticketPrice = parseInt(this.dataset.price);
                    selectedSeats.clear();
                    initBookingSeatMap();
                    updateOrderSummary();
                });
            });
        }

        // ---- Step navigation ----
        function initBookingSteps() {
            document.getElementById('toStep2').addEventListener('click', () => goToStep(2));
            document.getElementById('toStep3').addEventListener('click', () => goToStep(3));
            document.getElementById('toStep4').addEventListener('click', () => {
                goToStep(4);
                generateRef();
            });
            document.getElementById('back1').addEventListener('click', () => goToStep(1));
            document.getElementById('back2').addEventListener('click', () => goToStep(2));
        }

        function goToStep(n) {
            document.querySelectorAll('.booking-panel').forEach((p, i) => {
                p.classList.toggle('active', i + 1 === n);
            });
            document.querySelectorAll('.booking-step').forEach((s, i) => {
                const stepN = i + 1;
                s.classList.remove('active','done');
                if (stepN < n) s.classList.add('done');
                else if (stepN === n) s.classList.add('active');
            });
            window.scrollTo({ top: 0, behavior: 'smooth' });
        }

        function generateRef() {
            const ref = 'PULSE-2026-' + String(Math.floor(Math.random() * 99999) + 1).padStart(5,'0');
            document.getElementById('bookingRef').textContent = ref;
        }

        // ---- Payment method toggle ----
        function initPaymentMethods() {
            document.querySelectorAll('.payment-pill').forEach(pill => {
                pill.addEventListener('click', function () {
                    document.querySelectorAll('.payment-pill').forEach(p => p.classList.remove('active'));
                    this.classList.add('active');
                    const method = this.dataset.method;
                    document.getElementById('cardFields').style.display   = method === 'card'    ? 'block' : 'none';
                    document.getElementById('paynowFields').style.display = method === 'paynow'  ? 'block' : 'none';
                    document.getElementById('grabpayFields').style.display= method === 'grabpay' ? 'block' : 'none';
                });
            });

            // Card number formatting
            const cardInput = document.getElementById('cardNumber');
            if (cardInput) {
                cardInput.addEventListener('input', function () {
                    let v = this.value.replace(/\D/g,'').substring(0,16);
                    this.value = v.replace(/(.{4})/g,'$1 ').trim();
                });
            }
        }
        </script>

    </body>
</html>
